# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7049ad626dc04ef0d95beb91b257f73ed759337be48774d2c0dcb8cf9eac8fb685918e73e0d3aac52de5ca0b44f74e4657ed62602b5e2d83e4c23c4e7cc6a9be

test:
  secret_key_base: 20ad6dcf0db9d60c3650ee966c5b19ab05d81f9f88043a5a1d2137ddda94dc58ba7ed1ed0f90ec1ecb0368054a905deb0a6f37b7f5e3c08d7614e10cdbc260df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
